# Generated by Django 6.0.4 on 2026-04-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Untitled", max_length=255)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                ("color", models.CharField(choices=[("blue", "Blue"), ("red", "Red"), ("teal", "Teal"), ("purple", "Purple"), ("green", "Green")], default="blue", max_length=20)),
                ("participants", models.CharField(blank=True, max_length=255)),
                ("conferencing_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="calendar_events", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["start_at", "id"],
            },
        ),
    ]
