# Generated by Django 6.0.4 on 2026-04-24 00:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0002_calendarevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="calendarevent",
            name="students",
            field=models.ManyToManyField(blank=True, related_name="available_calendar_events", to=settings.AUTH_USER_MODEL),
        ),
    ]
